//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidApplicationDevelopment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public Filter()
        {
            this.Mails = new HashSet<Mail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual ICollection<Mail> Mails { get; set; }
    }
}
